// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9o3iNyD9IoIa3oiqw_vIG30xXjzTr2QU',
    appId: '1:552250045512:web:d0646878542a8be566147d',
    messagingSenderId: '552250045512',
    projectId: 'nutridiet-83fa5',
    authDomain: 'nutridiet-83fa5.firebaseapp.com',
    storageBucket: 'nutridiet-83fa5.firebasestorage.app',
    measurementId: 'G-6NXDWGHW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqCSSVpEh2dL2I2aLrLSOta-tV1YHBdY',
    appId: '1:552250045512:android:06e8a08129c2ccfa66147d',
    messagingSenderId: '552250045512',
    projectId: 'nutridiet-83fa5',
    storageBucket: 'nutridiet-83fa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuApJ6USg2cHb-_3IyeE5RpzbzBx9jyR8',
    appId: '1:552250045512:ios:f9a7dd741724b05f66147d',
    messagingSenderId: '552250045512',
    projectId: 'nutridiet-83fa5',
    storageBucket: 'nutridiet-83fa5.firebasestorage.app',
    androidClientId: '552250045512-3gv32a8him5420p1tiah04h1bk91nu6b.apps.googleusercontent.com',
    iosClientId: '552250045512-js8ek4nhk9u5d52jih8177digc0nabh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietPlanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuApJ6USg2cHb-_3IyeE5RpzbzBx9jyR8',
    appId: '1:552250045512:ios:f9a7dd741724b05f66147d',
    messagingSenderId: '552250045512',
    projectId: 'nutridiet-83fa5',
    storageBucket: 'nutridiet-83fa5.firebasestorage.app',
    androidClientId: '552250045512-3gv32a8him5420p1tiah04h1bk91nu6b.apps.googleusercontent.com',
    iosClientId: '552250045512-js8ek4nhk9u5d52jih8177digc0nabh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietPlanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9o3iNyD9IoIa3oiqw_vIG30xXjzTr2QU',
    appId: '1:552250045512:web:f23be5bd11a64c6566147d',
    messagingSenderId: '552250045512',
    projectId: 'nutridiet-83fa5',
    authDomain: 'nutridiet-83fa5.firebaseapp.com',
    storageBucket: 'nutridiet-83fa5.firebasestorage.app',
    measurementId: 'G-R0PG91J0GV',
  );
}
